apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: mungta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: mungtaregistry.azurecr.io/mungta/dev/user-service:latest
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: log-level
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: db-host
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mungta-credentials
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mungta-credentials
                  key: db-password
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mungta-credentials
                  key: mail-username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mungta-credentials
                  key: mail-password
